export const AllQurra = [
  {
    id: "3c7cc699-06cd-4609-bcd6-8b039d568f5b",
    identifier: "ar.abdulazizazzahrani",
    language: "ar",
    name: "عبد الباري محمد",
    englishName: "Abdulaziz Az-Zahrani",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "52fba8f9-8f99-4eef-8bd4-e6508aeecb98",
    identifier: "ar.abdulbariaththubaity",
    language: "ar",
    name: "عبدالعزيز الزهراني",
    englishName: "AbdulBari ath-Thubaity",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "4a221f7b-3e3d-4705-8a75-534ecf6dcd1c",
    identifier: "ar.abdulbarimohammed",
    language: "ar",
    name: "عبد الباري الثبيتي",
    englishName: "Abdul Bari Mohammed",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6bb4b1cc-8efa-4d11-97db-4bdf4aa97253",
    identifier: "ar.abdulbasitmujawwad",
    language: "ar",
    name: "عبد الباسط عبد الصمد [مجواد]",
    englishName: "AbdulBaset AbdulSamad [Mujawwad]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8810bc6e-4971-4401-88e3-3cbfd618bb19",
    identifier: "ar.abdulbasitmurattal",
    language: "ar",
    name: "عبد الباسط عبد الصمد [مرتال]",
    englishName: "AbdulBaset AbdulSamad [Murattal]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "a4c74e59-185b-4b94-baa1-dccae0988d3a",
    identifier: "ar.abdulkareemalhazmi",
    language: "ar",
    name: "عبد الكريم الحازمي",
    englishName: "Abdul-Kareem al-Hazmi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f1293a22-cda0-41a9-9a4f-938dbbb9cdde",
    identifier: "ar.abdullahalmatrood",
    language: "ar",
    name: "عبدالله المطرود",
    englishName: "Abdullah al-Matrood",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "5c856c24-aac7-4440-b139-d5b0ed18a178",
    identifier: "ar.abdullahawadaljuhani",
    language: "ar",
    name: "عبدالله الجهني",
    englishName: "Abdullah Juhany",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "25e39ac4-1b2d-4491-98ba-8d7740b34e53",
    identifier: "ar.abdullahbasfar",
    language: "ar",
    name: "عبدالله بصفر",
    englishName: "Abdullah Basfar",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8028bb37-0e5c-406a-b905-cc7a7a318f76",
    identifier: "ar.abdullahkhayat",
    language: "ar",
    name: "عبد الله خياط",
    englishName: "Abdullah Khayat",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "5abfc45a-b44f-41bd-8514-536c90933a86",
    identifier: "ar.abdullahkhulaifi",
    language: "ar",
    name: "عبدالله الخليفي",
    englishName: "Abdullah Khulayfee",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "97c7576f-674f-4f1c-abd0-d2163530eb9b",
    identifier: "ar.abdulmohsenalharthy",
    language: "ar",
    name: "عبدالمحسن الحارثي",
    englishName: "Abdulmohsen Al-Harthy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "27e0c066-552e-4cf1-ac11-573e4353cf17",
    identifier: "ar.abdulmuhsinalqasim",
    language: "ar",
    name: "عبدالمحسن القاسم",
    englishName: "AbdulMuhsin al-Qasim",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "acc01539-09cd-48e6-a5fb-0490c6a5c041",
    identifier: "ar.abdulmunimabdulmubdi",
    language: "ar",
    name: "عبد المنعم عبد المبتكر",
    englishName: "Abdul-Mun'im Abdul-Mubdi'",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "388ac316-2b2c-4e87-9d8c-73e01a17921d",
    identifier: "ar.abdulwadoodhaneef",
    language: "ar",
    name: "عبدالودود حنيف",
    englishName: "AbdulWadood Haneef",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "e02c10b3-ffdf-4aab-a119-9948122f0873",
    identifier: "ar.abdurrasheedsufiabialhaarithanalkasaaee",
    language: "ar",
    name: "عبد الرشيد الصوفي [أبي الحارث عن الكسائي]",
    englishName: "Abdur-Rashid Sufi [Abi al-Haarith an al-Kasaa’ee]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "e86ef610-bf3d-4058-b92f-c8958ca6bd2d",
    identifier: "ar.abdurrasheedsufiaddoorianabiamr",
    language: "ar",
    name: "عبد الرشيد الصوفي [الدوري عن أبي عمرو]",
    englishName: "Abdur-Rashid Sufi [ad-Doori an Abi Amr]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "062ec766-f435-466d-9a43-ed228955172e",
    identifier: "ar.abdurrasheedsufishubahanasim",
    language: "ar",
    name: "عبد الرشيد صوفي [شعبة عن عاصم]",
    englishName: "Abdur-Rashid Sufi [Shu'bah an Asim]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "be37f034-b966-429e-b360-8cc0d7e98874",
    identifier: "ar.abdurrasheedsufisoosi",
    language: "ar",
    name: "عبد الرشيد الصوفي [السوسي]",
    englishName: "Abdurrashid Sufi [Soosi]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b194901c-448e-4ab8-ab81-f731ef794f2c",
    identifier: "ar.abdurrazaqbinabtanaldulaimi",
    language: "ar",
    name: "عبد الرزاق بن عبطان الدليمي",
    englishName: "Abdur Razaq Bin Abtan Al Dulaimi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "ffe9a624-8fdf-468c-9d10-fbe272b9e475",
    identifier: "ar.abuabdullahmuniraltounsi",
    language: "ar",
    name: "أبو عبد الله منير التونسي",
    englishName: "Abu Abdullah Munir Al Tounsi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b956e256-a253-4961-9fa6-247052da6485",
    identifier: "ar.abubakraldhabi",
    language: "ar",
    name: "أبو بكر الظبي",
    englishName: "Abu Bakr al Dhabi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "882bfe78-8c5b-4a2f-87d0-cfac34bdbe4f",
    identifier: "ar.adilkalbani",
    language: "ar",
    name: "عادل الكلباني",
    englishName: "Adel Kalbani",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "7c58b193-f1d5-48ac-8031-35a82e07050f",
    identifier: "ar.ahmadalhawashy",
    language: "ar",
    name: "احمد الحواشي",
    englishName: "Ahmad Al Hawashy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0dba550e-eaa0-439b-84cf-0a4768bf40aa",
    identifier: "ar.ahmadalnufais",
    language: "ar",
    name: "احمد النفيس",
    englishName: "Ahmad Alnufais",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "928b1f90-1501-4fcc-8c14-54a83e13ba68",
    identifier: "ar.ahmadkhaderaltarabulsi",
    language: "ar",
    name: "أحمد خضر الطرابلسي",
    englishName: "Ahmad Khader Al-Tarabulsi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "2455a520-7eb4-4344-bdd8-02e80d083f7d",
    identifier: "ar.ahmadsulaiman",
    language: "ar",
    name: " أحمد سليمان ",
    englishName: "Ahmad Suleiman",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0e53566b-0ab8-4888-90a0-080e067c2921",
    identifier: "ar.ahmedalajmi",
    language: "ar",
    name: "أحمد بن علي العجمي",
    englishName: "Ahmed ibn Ali al-Ajamy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "73d49b38-168e-4322-99f7-51759ffe71e3",
    identifier: "ar.ahmedalhammad",
    language: "ar",
    name: "احمد الحماد",
    englishName: "Ahmed Al Hammad",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "eeb86040-6479-47e5-a6e2-923d00bc8a33",
    identifier: "ar.ahmedalmisbahi",
    language: "ar",
    name: "احمد المصباحي",
    englishName: "Ahmed Al Misbahi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "eec9df24-21fe-4baf-8883-c1fbb9e02c44",
    identifier: "ar.ahmedamir",
    language: "ar",
    name: "احمد امير",
    englishName: "Ahmed Amir",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "1d681000-d001-49d3-a24e-5ec33b89125b",
    identifier: "ar.ahmedmohamedsalama",
    language: "ar",
    name: "أحمد محمد سلامة",
    englishName: "Ahmed Mohamed Salama",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0d11d5c0-61ef-4e2a-b2e4-9bc9cf06e3ef",
    identifier: "ar.ahmedsaber",
    language: "ar",
    name: "احمد صابر",
    englishName: "Ahmed Saber",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6b82e146-5804-4c2b-b065-45cd5fc6d453",
    identifier: "ar.alafasy",
    language: "ar",
    name: "مشاري راشد العفاسي",
    englishName: "Mishary Rashid Alafasy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "33cb6924-6d55-47e3-83f8-79c5f09f848e",
    identifier: "ar.alashryomran",
    language: "ar",
    name: "العشري عمران",
    englishName: "Al Ashry Omran",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8e738ebd-3b25-41cc-8f4c-ba35790657b8",
    identifier: "ar.alfatehmuhammadzubair",
    language: "ar",
    name: "الفاتح محمد الزبير",
    englishName: "Al Fateh Muhammad Zubair",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "9151ebaa-3bab-44d2-9e53-080d1a99e5ba",
    identifier: "ar.alhusaynialazazi",
    language: "ar",
    name: "الحسيني العزازي",
    englishName: "Al Husayni Al Azazi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8ff91a39-6268-4e96-b9ab-d778e4094886",
    identifier: "ar.alhusaynialazazichildren",
    language: "ar",
    name: "الحسيني العزازي - أطفال",
    englishName: "Al Husayni Al Azazi - Children",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "3d83a8a4-68d6-4bec-9d5e-c196466e0d97",
    identifier: "ar.aliabdurrahmanalhuthaify",
    language: "ar",
    name: "علي عبدالرحمن الحذيفي",
    englishName: "Ali Abdur-Rahman al-Huthaify",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0dd7e3c1-d0ca-4a4a-86c8-c09e4cd38639",
    identifier: "ar.aliabdurrahmanalhuthaifyqaloon",
    language: "ar",
    name: "علي الحذيفي [قالون]",
    englishName: "Ali al-Huthaify [Qaaloon]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "621078a6-d1fe-4bd8-a3af-8173019eba72",
    identifier: "ar.alihajjajsouissi",
    language: "ar",
    name: "علي حجاج السويسي",
    englishName: "Ali Hajjaj Souissi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b7e7088e-c08d-476a-a411-8c5944fab1b0",
    identifier: "ar.alzainmohamedahmed",
    language: "ar",
    name: "الزين محمد أحمد",
    englishName: "Alzain Mohammad Ahmad",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "e1cbb0b3-97af-4e5c-8261-e55eb43df815",
    identifier: "ar.aymanswed",
    language: "ar",
    name: "أيمن سويد",
    englishName: "Ayman Swed",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "ccce552f-5191-4ac9-a27c-ac11fd93f964",
    identifier: "ar.azizalili",
    language: "ar",
    name: "عزيز عليلي",
    englishName: "Aziz Alili",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6db0345f-b4ed-4aef-9248-3e94c7f4b269",
    identifier: "ar.bandarbalila",
    language: "ar",
    name: "بندر بليلة",
    englishName: "Bandar Balila",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "63d5b233-e19b-4b47-ad01-bf1453935f6c",
    identifier: "ar.basselabdulrahmanraoui",
    language: "ar",
    name: "باسل عبد الرحمن راوي",
    englishName: "Bassel Abdul Rahman Raoui",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "fe2560ef-17c8-4274-a171-32403e3556c7",
    identifier: "ar.benkirane",
    language: "ar",
    name: "عبد المجيب بن كيران",
    englishName: "عبد المجيب بن كيران",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "1d3b5a51-3a31-4b4c-ab5d-2f3d93bd9643",
    identifier: "ar.darwishfarajdarwishalattar",
    language: "ar",
    name: "درويش فرج درويش العطار",
    englishName: "Darwish Faraj Darwish Al Attar",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "61af58de-7aba-49e3-a3cd-64ecd768c383",
    identifier: "ar.eidhassanabuaachra",
    language: "ar",
    name: "عيد حسن أبو عشرة",
    englishName: "Eid Hassan Abu Aachra",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f149b059-48ab-4d96-8c17-3dd90bcd5e88",
    identifier: "ar.emadalmansary",
    language: "ar",
    name: "عماد المنصري",
    englishName: "Emad Al Mansary",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d84e9afc-79c2-46b7-9f2f-cc78300780ab",
    identifier: "ar.ezzatsabri",
    language: "ar",
    name: "عزت صبري",
    englishName: "Ezzat Sabri",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d5c31ff3-ec89-4f6b-944b-4c75c5705529",
    identifier: "ar.faresabbad",
    language: "ar",
    name: "فارس عباد",
    englishName: "Fares Abbad",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d12e2a1a-f1dd-4eae-9b61-2c4b2958d786",
    identifier: "ar.fouadalkhamiri",
    language: "ar",
    name: "فؤاد الخميري",
    englishName: "Fouad Al Khamiri",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "cb32f67f-17dc-45b4-9321-366da2fe1eaa",
    identifier: "ar.hamadsinan",
    language: "ar",
    name: "حمد سنان",
    englishName: "Hamad Sinan",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "fa506a29-7f8a-48c3-aecd-8facdeea564a",
    identifier: "ar.hamdyalsayedtolbasaad",
    language: "ar",
    name: "حمدي السيد طلبة سعد",
    englishName: "Hamdy Al Sayed Tolba Saad",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "7f8271b0-2819-4f1f-a1bf-c1f6c4e67bc5",
    identifier: "ar.haniarrifai",
    language: "ar",
    name: "هاني الرفاعي",
    englishName: "Hani ar-Rifai",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "42a3852a-5061-41db-a0cf-306b96e3adde",
    identifier: "ar.hasanhashem",
    language: "ar",
    name: "حسن هاشم",
    englishName: "Hasan Hashem",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "2462d3d6-b464-4da8-951c-1138aef5452f",
    identifier: "ar.hassansaleh",
    language: "ar",
    name: "حسن صالح",
    englishName: "Hasan Saleh",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "e42c247d-2333-4ed0-80ba-8404a1d67b60",
    identifier: "ar.hatemfarid",
    language: "ar",
    name: "حاتمفريد",
    englishName: "hatemfarid",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "96a6d143-ba84-43d9-bf79-e3970268ddb8",
    identifier: "ar.ibrahimalakhdar",
    language: "ar",
    name: "إبراهيم الأخضر",
    englishName: "Ibrahim Al Akhdar",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "124bd6ba-3999-47ae-9880-9d61333f5e9a",
    identifier: "ar.ibrahimaldossari",
    language: "ar",
    name: "إبراهيم الدوسري",
    englishName: "Ibrahim Al Dossari",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "c7cb213c-3428-4bfc-a93c-31e3957e33f5",
    identifier: "ar.ibrahimaljormy",
    language: "ar",
    name: "إبراهيم الجرمي",
    englishName: "Ibrahim Aljormy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "215bffa2-52e9-4a7c-9b56-91c2b35a1ac4",
    identifier: "ar.ilhantok",
    language: "ar",
    name: "إلهان توك",
    englishName: "Ilhan Tok",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0789d8e0-31b0-4b4e-8a05-56e37e0180df",
    identifier: "ar.imadzuhairhafez",
    language: "ar",
    name: "عماد زهير حافظ",
    englishName: "Imad Zuhair Hafez",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6acda9f8-3443-461b-9e84-c3a5f7583465",
    identifier: "ar.jaberabdulhameed",
    language: "ar",
    name: "جابر عبد الحميد",
    englishName: "Jaber Abdul Hameed",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "3d0b52c7-4674-4b35-acf6-4ea1761588b1",
    identifier: "ar.jamaanalosaimi",
    language: "ar",
    name: "جمعان العصيمي",
    englishName: "Jamaan Alosaimi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "517da558-211a-401a-8f22-5eeff0cbfaea",
    identifier: "ar.jamalshakerabdullah",
    language: "ar",
    name: "جمال شاكر عبدالله",
    englishName: "Jamal Shaker Abdullah",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "da0fe145-5f0d-4526-a312-94293ec88e9f",
    identifier: "ar.jazzaalswaileh",
    language: "ar",
    name: "جازة الصويلح",
    englishName: "Jazza Alswaileh",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0cca2480-cd57-4a2d-943a-291466dfc05e",
    identifier: "ar.kamel",
    language: "ar",
    name: "عبد الله كامل",
    englishName: "Abdallah Kamel",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "61985b50-4f16-4d2d-b7c3-e249babb4358",
    identifier: "ar.karimmansouri",
    language: "ar",
    name: "كريم المنصوري",
    englishName: "Karim Mansouri",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "fc4b3027-2eb9-410f-8a74-e6ce64ac397e",
    identifier: "ar.khaledalqahtani",
    language: "ar",
    name: "خالد عبدالله القحطاني",
    englishName: "Khaalid Abdullaah al-Qahtaanee",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "eb2afff4-9cc1-4a93-b560-85e22e963736",
    identifier: "ar.khaledbarakat",
    language: "ar",
    name: "خالد بركات",
    englishName: "Khaled Barakat",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "05a87fb2-7d8a-43d1-923c-706d6104ea12",
    identifier: "ar.khalidabdulkafi",
    language: "ar",
    name: "خالد عبد الخافي",
    englishName: "Khalid Abdulkhafi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "cc3e0875-973a-49e1-9a40-6802ea185ae7",
    identifier: "ar.khalidaljalil",
    language: "ar",
    name: "خالد الجليل",
    englishName: "Khalid Al Jalil",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "33edfc39-7b35-4275-9442-452dd1855d62",
    identifier: "ar.khalidalmohanna",
    language: "ar",
    name: "خالد المهنعنة",
    englishName: "Khalid Al-Moh'n'na",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "42793a04-c86c-4eb8-94e3-01b9061e592b",
    identifier: "ar.khalifaaltunaiji",
    language: "ar",
    name: "خليفة الطنيجي",
    englishName: "Khalifah At-Tonaeijy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "381ac1c9-1a5f-46ce-9fdf-2f768f62eb9a",
    identifier: "ar.laayounelkouchi",
    language: "ar",
    name: "عيون الكوشي",
    englishName: "Laayoun El Kouchi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "1c982498-744b-4698-b6cc-30a172d52610",
    identifier: "ar.lesaintcorantraduitenfrancais",
    language: "ar",
    name: "لو سانت كوران",
    englishName: "Le Saint Coran Traduit En Francais",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0ab2325a-4cad-4b0a-b222-805b6c0c5ce0",
    identifier: "ar.mahershakhashiro",
    language: "ar",
    name: "ماهر شخاشيرو",
    englishName: "Maher Shakhashero",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "cb4bb22a-eab7-4c4e-91ca-c814ef26d1e0",
    identifier: "ar.mahmoodalrifai",
    language: "ar",
    name: "محمود الرفاعي",
    englishName: "Mahmod Alrifai",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "5b20109a-cc13-41f8-8605-0939dddf50ab",
    identifier: "ar.mahmoudalialbanna",
    language: "ar",
    name: "محمود علي البنا",
    englishName: "Mahmud Ali Al Banna",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6caad157-0b7f-4d88-abd2-8a4ca7c6b33b",
    identifier: "ar.mahmoudelsheimy",
    language: "ar",
    name: "محمود الشيمي",
    englishName: "Mahmoud El Sheimy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "09e6e1a0-9e8b-4e94-a329-ebad5311b5e0",
    identifier: "ar.mahmoudsaaddarouich",
    language: "ar",
    name: "محمود سعد درويش",
    englishName: "Mahmoud Saad Darouich",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b14eb82a-d030-44a5-ad12-c4d1aedc16c0",
    identifier: "ar.mahmoudsayedeltayeb",
    language: "ar",
    name: "محمود سيد الطيب",
    englishName: "Mahmoud Sayed Eltayeb",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "ad03b6ca-45c9-40e4-a739-c9e3294e5d7c",
    identifier: "ar.misharyrashidalafasy",
    language: "ar",
    name: "مشاري راشد العفاسي",
    englishName: "Mishary Rashid Alafasy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "51f916b0-bc44-43c1-bc7b-ae3b95b2ec00",
    identifier: "ar.moeedhalharthi",
    language: "ar",
    name: "معيض الحارثي",
    englishName: "Moeedh Al-Harthi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "eca9700a-611b-4d45-ac8d-d68052f6b9ad",
    identifier: "ar.mohamedabdelaziz",
    language: "ar",
    name: "محمد عبد العزيز",
    englishName: "Mohamed Abdelaziz",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "ad6e17fa-a5be-4fe1-89d7-9216260a6f73",
    identifier: "ar.mohamedabdelhakimsaadalabdullah",
    language: "ar",
    name: "محمد عبد الحكيم سعد العبد الله",
    englishName: "Mohamed Abdel Hakim Saad Al Abdullah",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "122134ec-bd3d-4a5a-94d7-18d507b035ff",
    identifier: "ar.mohamedaljaberyalheyani",
    language: "ar",
    name: "محمد الجابري الحياني",
    englishName: "Mohamed Aljabery Al Heyani",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "67b3ebf8-781a-48bc-af39-eff8ad576b05",
    identifier: "ar.mohamedalmohisni",
    language: "ar",
    name: "محمد المحيسني",
    englishName: "Mohamed Al Mohisni",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "df35f1a1-bbf8-4f56-be5b-0fe938d095cc",
    identifier: "ar.mohamedelkantaoui",
    language: "ar",
    name: "محمد القنطاوي",
    englishName: "Mohamed El Kantaoui",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0c1687b6-ad68-4d9a-8d83-b37b349a94da",
    identifier: "ar.mohamedhassan",
    language: "ar",
    name: "محمد حسن",
    englishName: "Muhammad Hassan",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "ed84e843-3dd9-410c-88dc-177b2da4c82b",
    identifier: "ar.mohamedmaabad",
    language: "ar",
    name: "محمد معبد",
    englishName: "Mohamed Maabad",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f16ce1c5-a936-49e8-9892-fa8a2683e542",
    identifier: "ar.mohamedosmankhan",
    language: "ar",
    name: "محمد عثمان خان (من الهند)",
    englishName: "Mohammed Osman Khan (from India)",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "35532445-4908-4f29-8b4c-00a2a3eb00f2",
    identifier: "ar.mohamedshaabanabuqarn",
    language: "ar",
    name: "محمد شعبان أبو قرن",
    englishName: "Mohamed Shaaban Abu Qarn",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "02c7eb0e-2726-4f0b-8cb3-ea5380a7304c",
    identifier: "ar.mohamedtablawi",
    language: "ar",
    name: "محمد الطبلاوي",
    englishName: "Mohamed Al-Tablawi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "3978b360-a6ed-4d36-bf2b-d6d01b54324b",
    identifier: "ar.mohammadismaeelalmuqaddim",
    language: "ar",
    name: "محمد إسماعيل المقدم",
    englishName: "Mohammad Ismaeel Al-Muqaddim",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "c9638b27-f237-49f0-90a8-7e16484ae1e2",
    identifier: "ar.mohammadrachadalshareef",
    language: "ar",
    name: "محمد رشاد الشريف",
    englishName: "Mohammad Rachad Al Shareef",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "83dd2315-edf0-439f-aa90-b96ccaa4fc23",
    identifier: "ar.mohammedbinsalehabuzaid",
    language: "ar",
    name: "محمد بن صالح أبو زيد",
    englishName: "Mohammed Bin Saleh Abu Zaid",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "487aa21e-7cd6-4972-b9af-a4ed73a546ac",
    identifier: "ar.muftahalsaltany",
    language: "ar",
    name: "مفتاح السلطاني",
    englishName: "Moftah AlSultany",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d8398555-234d-4ad5-8ad2-7ece92865018",
    identifier: "ar.muhammadabdulkareem",
    language: "ar",
    name: "محمد عبد الكريم",
    englishName: "Muhammad AbdulKareem",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b3254d4a-1855-45de-b308-26acfc635ba3",
    identifier: "ar.muhammadalaalimaldokali",
    language: "ar",
    name: "محمد العالم الدكالي",
    englishName: "Muhammad Al Aalim Al Dokali",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f2c8788b-58bc-4d8a-994e-053330fa4b51",
    identifier: "ar.muhammadalluhaidan",
    language: "ar",
    name: "محمد الهيدان",
    englishName: "Mohammad Al-Haid'an",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d852d2ab-0900-4223-a567-659082eb50d6",
    identifier: "ar.muhammadalmehysni",
    language: "ar",
    name: "محمد المحيسني",
    englishName: "Muhammad al-Muhaisny",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "2b875dfe-88b7-46a4-bdd1-d9e5cd25f37d",
    identifier: "ar.muhammadalsubayyil",
    language: "ar",
    name: "محمد صبيل",
    englishName: "Muhammad Subbayil",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "30a95fd3-9ff0-404b-a5ea-cad5d65a205f",
    identifier: "ar.muhammadanwarshahat",
    language: "ar",
    name: "محمد أنور الشحات",
    englishName: "Muhammad Anwar Shahat",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b14c66a1-0d0e-4c96-bf78-2c046de77005",
    identifier: "ar.muhammadayyub",
    language: "ar",
    name: "محمد أيوب",
    englishName: "Mohammad Ayyub",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6f0b9899-a60e-45d0-b4f0-69d4932d9bb7",
    identifier: "ar.muhammadsalehalimshah",
    language: "ar",
    name: "محمد صالح شاه",
    englishName: "Mohammad Saleh Shah",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "a92631bb-8fb7-4a82-894c-81cc3ae20a94",
    identifier: "ar.muhammadsiddiqalminshawimujawwad",
    language: "ar",
    name: "محمد صديق المنشاوي [مجواد]",
    englishName: "Muhammad Siddeeq al-Minshawi [Mujawwad]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "364600dd-21a7-4cf9-8999-a1163f46437b",
    identifier: "ar.muhammadsulaimanpatel",
    language: "ar",
    name: "محمد سليمان باتل",
    englishName: "Muhammad Sulaiman Patel",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "2ef98d22-62bd-4526-b2ca-03169dd8333b",
    identifier: "ar.musabilal",
    language: "ar",
    name: "موسى بلال",
    englishName: "Musa Bilal",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "c7067cb9-3a10-4d88-9dbd-ec7e9e2afc78",
    identifier: "ar.mustafaallahouni",
    language: "ar",
    name: "مصطفى اللاهوني",
    englishName: "Mustafa Al-Lahoni",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "5e1e4206-6650-40a5-abc4-afb1ee959cca",
    identifier: "ar.mustafaismail",
    language: "ar",
    name: "مصطفى إسماعيل",
    englishName: "Mostafa Ismaeel",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "7d66a416-a695-4505-b788-6c9336d89a69",
    identifier: "ar.mustafaraadalazzawi",
    language: "ar",
    name: "مصطفى رعد العزاوي",
    englishName: "Mustafa Ra'ad Al-Azawi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6efa5029-e5fb-415d-bcb2-45acfca6472d",
    identifier: "ar.mustaphagharbi",
    language: "ar",
    name: "مصطفى الغربي",
    englishName: "Mustapha Gharbi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "113912a7-0ffc-4ceb-a28a-6894b8d37a1a",
    identifier: "ar.nabilarrifai",
    language: "ar",
    name: "نبيل الرفاعي",
    englishName: "Nabil Ar-Rifa'i",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "19e8e0ff-004e-426a-8cf0-2723db19727a",
    identifier: "ar.nasseralqatami",
    language: "ar",
    name: "ناصر القطامي",
    englishName: "Nasser Alqatami",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "bd8f7aa6-5d06-4df2-997c-e5b364cc4dfe",
    identifier: "ar.neamahalhassan",
    language: "ar",
    name: "نعمة الحسن",
    englishName: "N'amah Alhassan",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "27c8bf35-0687-4e78-ba61-e76a83a4f4ca",
    identifier: "ar.obeikan",
    language: "ar",
    name: "عبدالمحسن العبيكان",
    englishName: "Abdul Mohsen Al Obeikan",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b2e2eaf7-18f3-422f-887b-a0ae97f31f7d",
    identifier: "ar.oimaoqataris",
    language: "ar",
    name: "ايماو قطريين",
    englishName: "Oimao Qataris",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b646422c-67ad-44bb-9fe7-c17a2be6f751",
    identifier: "ar.omaralkazabri",
    language: "ar",
    name: "عمر الكزابري",
    englishName: "Omar Al Kazabri",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "ea563001-fcd6-40cf-bca3-8bb41c646012",
    identifier: "ar.osamabinalialghanim",
    language: "ar",
    name: "أسامة بن علي الغانم",
    englishName: "Osama Bin Ali Al Ghanim",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b18a1282-31c6-47b7-9277-ecf592cb8b03",
    identifier: "ar.rachidbelalia",
    language: "ar",
    name: "رشيد بلعليا",
    englishName: "Rachid Belalia",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f9d899db-dfcf-4fa1-9577-06fddab3db1c",
    identifier: "ar.saberabdulhakam",
    language: "ar",
    name: "صابر عبد الحكم",
    englishName: "Saber Abdul-hakam",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "722ee63d-f6f9-478a-81a2-c220ec72f541",
    identifier: "ar.sadaqatali",
    language: "ar",
    name: "صدقات علي",
    englishName: "Sadaqat Ali",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d86b38c7-81d8-4d08-8b92-d95c7fd4d195",
    identifier: "ar.sahlyasin",
    language: "ar",
    name: "سهل ياسين",
    englishName: "Sahl Yaaseen",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "54542dda-ae38-4996-b01b-eab59c7284d8",
    identifier: "ar.saidalshaalan",
    language: "ar",
    name: "سعيد الشعلان",
    englishName: "Said Al Shaalan",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "db6752db-5141-443f-a355-e518ff871d3b",
    identifier: "ar.salahalbudair",
    language: "ar",
    name: "صلاح البدير",
    englishName: "Salah Al-Budair",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "6b94a57b-82cf-42fb-b8bd-35d44effd1ec",
    identifier: "ar.salahalhashem",
    language: "ar",
    name: "صلاح الهاشم",
    englishName: "Salah Alhashim",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "afc8e187-5ad2-4a2e-9d01-a1d3a506c0b5",
    identifier: "ar.salahbaothman",
    language: "ar",
    name: "صلاح باعثمان",
    englishName: "Salah Baothman",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "00d3610c-c5bf-4378-a5c0-b7e51235c87a",
    identifier: "ar.samirbelaachya",
    language: "ar",
    name: "سمير بلعشية",
    englishName: "Samir Belaachya",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "02988db1-88f2-415e-b4df-3d6cbcafa816",
    identifier: "ar.saudalshuraim",
    language: "ar",
    name: "سعود الشريم",
    englishName: "Sa'ud al-Shuraym",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f0bb19e4-47d6-45b4-ae18-86114bf86c34",
    identifier: "ar.sayedramadan",
    language: "ar",
    name: "الشيخ سيد رمضان",
    englishName: "Sheikh Syed Ramadan",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f3ec6eb0-7937-4477-8373-e1246263ff2d",
    identifier: "ar.shahriarparhizgar",
    language: "ar",
    name: "شهريار بارهيزجار",
    englishName: "Shahriar Parhizgar",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8283f44e-e1c7-4a0b-9936-46542ae5eb1a",
    identifier: "ar.sudaisshuraymnaeemsultan",
    language: "ar",
    name: "الشيخ السديس والشيخ شريم مع نعيم سلطان [ترجمة بيكثال]",
    englishName:
      "Shaykh Sudais and Shaykh Shuraim with Naeem Sultan [Pickthall Translation]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "0eebdd85-0464-44bf-97a7-71ac74675c6a",
    identifier: "ar.tamerislam",
    language: "ar",
    name: "تامر إسلام",
    englishName: "Tamer Islam",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "e4700c96-101c-4c20-8d00-999adffe7967",
    identifier: "ar.tareqabdulganidaawob",
    language: "ar",
    name: "طارق دعوب",
    englishName: "Tareq Daawob",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f9949071-42a3-4cba-bbd4-90bdd0d90da6",
    identifier: "ar.tawfeeqassayegh",
    language: "ar",
    name: "توفيق الصايغ",
    englishName: "Tawfeeq As-Sayegh",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "e15cd5e4-c5bd-46b4-8aa7-964c3d71843f",
    identifier: "ar.turkiebeidalmarri",
    language: "ar",
    name: "تركي عبيد المري",
    englishName: "Turki Ebeid Al Marri",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8a00a7ea-3cf5-4b99-80c6-9b62ad5556d2",
    identifier: "ar.waeldesouky",
    language: "ar",
    name: "وائل دسوقي",
    englishName: "Wael Desouky",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "d1d8061f-7bd8-4a11-b63e-0a7bd7f39c8c",
    identifier: "ar.waelradwanqureshi",
    language: "ar",
    name: "وائل رضوان قريشي",
    englishName: "Wael Radwan Qureshi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "9d02dea8-2ba6-46f2-9cb8-b2044b39d67b",
    identifier: "ar.waleedidreesalmaneese",
    language: "ar",
    name: "وليد إدريس المنيسي",
    englishName: "Waleed Idrees Al Maneese",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "4bd928b4-c6e4-43a0-8c67-324c490d6c3c",
    identifier: "ar.waleednaehi",
    language: "ar",
    name: "وليد النعيمي",
    englishName: "Waleed AlNa'ehi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "5e8802d5-05c7-4951-a40a-28f0c89eb4d2",
    identifier: "ar.waleedsamiraliabdulmajidsorour",
    language: "ar",
    name: "وليد سمير علي عبد المجيد سرور",
    englishName: "Waleed Samir Ali Abdul Majid Sorour",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "f3e88c52-0ac8-4974-9ab0-54565a464371",
    identifier: "ar.walidalshatti",
    language: "ar",
    name: "وليد الشطي",
    englishName: "Walid Al Shatti",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "56945c68-2f10-4809-a8c5-0e840cef3e31",
    identifier: "ar.walidfathibashta",
    language: "ar",
    name: "وليد فتحي بشتا",
    englishName: "Walid Fathi Bashta",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "a9b28225-ccc5-440b-9400-94081aa84cca",
    identifier: "ar.yahyahawwa",
    language: "ar",
    name: "يحيى حوا",
    englishName: "Yahya Hawwa",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "af63b426-9a12-4f7c-b837-b0c6fc6174d8",
    identifier: "ar.yassenaljazairi",
    language: "ar",
    name: " ياسين الجزائري ",
    englishName: "Yassen Al Jazairi",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "446c3789-66f5-4bb5-bac0-ef7889ea14b5",
    identifier: "ar.yasseraldossari",
    language: "ar",
    name: "ياسر الدوسري",
    englishName: "Yasser Al_Dosari",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "1c66228a-c7f6-477c-81ed-16c6a705d4e3",
    identifier: "ar.yasseralmazroyee",
    language: "ar",
    name: "ياسر المزروعي",
    englishName: "Yasser Al-Mazroey",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "9638c09d-5f84-4975-91ce-32209f87eaa9",
    identifier: "ar.yasserqureshi",
    language: "ar",
    name: "ياسر القرشي",
    englishName: "Yasser AlKurashy",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "b42444e2-82fa-43aa-b1da-d2f2272fa36f",
    identifier: "ar.yassersalama",
    language: "ar",
    name: "ياسر سلامة",
    englishName: "Yasser Salama",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "52a0e148-9be1-4ef8-8e55-c28d3097d338",
    identifier: "ar.yassersarhaneldeeb",
    language: "ar",
    name: "ياسر سرحان الديب",
    englishName: "Yasser Sarhan Eldeeb",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "8c47666f-9999-46e5-b16c-148606eae9b5",
    identifier: "ar.yousufalshoaey",
    language: "ar",
    name: "يوسف الشويعي",
    englishName: "Yousef Al-Shoowayie'e",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "3bc3fbcd-b263-4db7-bf08-07f6156f8fcb",
    identifier: "ar.yousufbinnoahahmad",
    language: "ar",
    name: "يوسف بن نوح أحمد",
    englishName: "Yusuf Bin Noah Ahmed",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "dd50a9f6-2afc-4f0d-aa5e-0291dd361aca",
    identifier: "en.misharyrashidalafasyenglishtranslationsaheehibrahimwalk",
    language: "ar",
    name: "مشاري راشد مع إبراهيم ووك [ترجمة صحيحة دولية]",
    englishName: "Mishaari Raashid with Ibrahim Walk [Saheeh Intl Translation]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "7c181bcb-f435-4d87-8454-71d1e3d1f1f3",
    identifier: "en.muhammadayyubenglishtranslationmuhsinkhanmikaalwaters",
    language: "ar",
    name: "محمد أيوب مع ميكال ووترز [ترجمة محسن خان]",
    englishName: "Muhammad Ayoob with Mikaal Waters [Muhsin Khan Translation]",
    format: "audio",
    type: "surahbysurah",
  },
  {
    id: "25a1c5e9-9a99-46a3-8249-19d9cac17ddc",
    identifier: "en.sudaisandshuraymenglishtranslationpickthallaslamathar",
    language: "ar",
    name: "السديس والشريم مع أسلم أثر [ترجمة بيكثال]",
    englishName: "Sodais and Shuraim with Aslam Athar [Pickthall Translation]",
    format: "audio",
    type: "surahbysurah",
  },
];
