import { v4 as uuidv4 } from "uuid";

export const Countrys = [
  {
    id: 0,
    name: "السويد",
    Countryiso: "SE",
    cities: [
      { id: uuidv4(), name: "Älvsbyn" },
      { id: uuidv4(), name: "Åmål" },
      { id: uuidv4(), name: "Aneby" },
      { id: uuidv4(), name: "Ånge" },
      { id: uuidv4(), name: "Ängelholm" },
      { id: uuidv4(), name: "Arboga" },
      { id: uuidv4(), name: "Åre" },
      { id: uuidv4(), name: "Årjäng" },
      { id: uuidv4(), name: "Arjeplog" },
      { id: uuidv4(), name: "Arvidsjaur" },
      { id: uuidv4(), name: "Arvika" },
      { id: uuidv4(), name: "Åsele" },
      { id: uuidv4(), name: "Askersund" },
      { id: uuidv4(), name: "Åstorp" },
      { id: uuidv4(), name: "Åtvidaberg" },
      { id: uuidv4(), name: "Avesta" },
      { id: uuidv4(), name: "Båstad" },
      { id: uuidv4(), name: "Bengtsfors" },
      { id: uuidv4(), name: "Berg" },
      { id: uuidv4(), name: "Bjurholm" },
      { id: uuidv4(), name: "Bjuv" },
      { id: uuidv4(), name: "Boden" },
      { id: uuidv4(), name: "Bollebygd" },
      { id: uuidv4(), name: "Bollnäs" },
      { id: uuidv4(), name: "Borås" },
      { id: uuidv4(), name: "Borgholm" },
      { id: uuidv4(), name: "Borlänge" },
      { id: uuidv4(), name: "Botkyrka" },
      { id: uuidv4(), name: "Boxholm" },
      { id: uuidv4(), name: "Bräcke" },
      { id: uuidv4(), name: "Bromölla" },
      { id: uuidv4(), name: "Burlöv" },
      { id: uuidv4(), name: "Dals-Ed" },
      { id: uuidv4(), name: "Danderyd" },
      { id: uuidv4(), name: "Degerfors" },
      { id: uuidv4(), name: "Dorotea" },
      { id: uuidv4(), name: "Eda" },
      { id: uuidv4(), name: "Ekerö" },
      { id: uuidv4(), name: "Eksjö" },
      { id: uuidv4(), name: "Emmaboda" },
      { id: uuidv4(), name: "Enköping" },
      { id: uuidv4(), name: "Eskilstuna" },
      { id: uuidv4(), name: "Eslöv" },
      { id: uuidv4(), name: "Essunga" },
      { id: uuidv4(), name: "Fagersta" },
      { id: uuidv4(), name: "Falkenberg" },
      { id: uuidv4(), name: "Falköping" },
      { id: uuidv4(), name: "Falun" },
      { id: uuidv4(), name: "Färgelanda" },
      { id: uuidv4(), name: "Filipstad" },
      { id: uuidv4(), name: "Finspång" },
      { id: uuidv4(), name: "Flen" },
      { id: uuidv4(), name: "Forshaga" },
      { id: uuidv4(), name: "Gagnef" },
      { id: uuidv4(), name: "Gällivare" },
      { id: uuidv4(), name: "Gävle" },
      { id: uuidv4(), name: "Gislaved" },
      { id: uuidv4(), name: "Gnesta" },
      { id: uuidv4(), name: "Gnosjö" },
      { id: uuidv4(), name: "Göteborg" },
      { id: uuidv4(), name: "Götene" },
      { id: uuidv4(), name: "Gotland" },
      { id: uuidv4(), name: "Grästorp" },
      { id: uuidv4(), name: "Grums" },
      { id: uuidv4(), name: "Gullspång" },
      { id: uuidv4(), name: "Habo" },
      { id: uuidv4(), name: "Håbo" },
      { id: uuidv4(), name: "Hagfors" },
      { id: uuidv4(), name: "Hällefors" },
      { id: uuidv4(), name: "Hallsberg" },
      { id: uuidv4(), name: "Hallstahammar" },
      { id: uuidv4(), name: "Halmstad" },
      { id: uuidv4(), name: "Hammarö" },
      { id: uuidv4(), name: "Haninge" },
      { id: uuidv4(), name: "Haparanda" },
      { id: uuidv4(), name: "Härjedalen" },
      { id: uuidv4(), name: "Härnösand" },
      { id: uuidv4(), name: "Härryda" },
      { id: uuidv4(), name: "Hässleholm" },
      { id: uuidv4(), name: "Heby" },
      { id: uuidv4(), name: "Hedemora" },
      { id: uuidv4(), name: "Helsingborg" },
      { id: uuidv4(), name: "Herrljunga" },
      { id: uuidv4(), name: "Hjo" },
      { id: uuidv4(), name: "Hofors" },
      { id: uuidv4(), name: "Höganäs" },
      { id: uuidv4(), name: "Högsby" },
      { id: uuidv4(), name: "Höör" },
      { id: uuidv4(), name: "Hörby" },
      { id: uuidv4(), name: "Huddinge" },
      { id: uuidv4(), name: "Hudiksvall" },
      { id: uuidv4(), name: "Hultsfred" },
      { id: uuidv4(), name: "Hylte" },
      { id: uuidv4(), name: "Järfälla" },
      { id: uuidv4(), name: "Jokkmokk" },
      { id: uuidv4(), name: "Jönköping" },
      { id: uuidv4(), name: "Kalix" },
      { id: uuidv4(), name: "Kalmar" },
      { id: uuidv4(), name: "Karlsborg" },
      { id: uuidv4(), name: "Karlshamn" },
      { id: uuidv4(), name: "Karlskoga" },
      { id: uuidv4(), name: "Karlskrona" },
      { id: uuidv4(), name: "Karlstad" },
      { id: uuidv4(), name: "Katrineholm" },
      { id: uuidv4(), name: "Kävlinge" },
      { id: uuidv4(), name: "Kil" },
      { id: uuidv4(), name: "Kinda" },
      { id: uuidv4(), name: "Kiruna" },
      { id: uuidv4(), name: "Klippan" },
      { id: uuidv4(), name: "Knivsta" },
      { id: uuidv4(), name: "Köping" },
      { id: uuidv4(), name: "Kramfors" },
      { id: uuidv4(), name: "Kristianstad" },
      { id: uuidv4(), name: "Kristinehamn" },
      { id: uuidv4(), name: "Krokom" },
      { id: uuidv4(), name: "Kumla" },
      { id: uuidv4(), name: "Kungälv" },
      { id: uuidv4(), name: "Kungsbacka" },
      { id: uuidv4(), name: "Kungsör" },
      { id: uuidv4(), name: "Laholm" },
      { id: uuidv4(), name: "Landskrona" },
      { id: uuidv4(), name: "Laxå" },
      { id: uuidv4(), name: "Lekeberg" },
      { id: uuidv4(), name: "Leksand" },
      { id: uuidv4(), name: "Lerum" },
      { id: uuidv4(), name: "Lessebo" },
      { id: uuidv4(), name: "Lidingö" },
      { id: uuidv4(), name: "Lidköping" },
      { id: uuidv4(), name: "Lilla Edet" },
      { id: uuidv4(), name: "Lindesberg" },
      { id: uuidv4(), name: "Linköping" },
      { id: uuidv4(), name: "Ljungby" },
      { id: uuidv4(), name: "Ljusdal" },
      { id: uuidv4(), name: "Ljusnarsberg" },
      { id: uuidv4(), name: "Lomma" },
      { id: uuidv4(), name: "Ludvika" },
      { id: uuidv4(), name: "Luleå" },
      { id: uuidv4(), name: "Lund" },
      { id: uuidv4(), name: "Lycksele" },
      { id: uuidv4(), name: "Lysekil" },
      { id: uuidv4(), name: "Malå" },
      { id: uuidv4(), name: "Malmö" },
      { id: uuidv4(), name: "Malung-Sälen" },
      { id: uuidv4(), name: "Mariestad" },
      { id: uuidv4(), name: "Mark" },
      { id: uuidv4(), name: "Markaryd" },
      { id: uuidv4(), name: "Mellerud" },
      { id: uuidv4(), name: "Mjölby" },
      { id: uuidv4(), name: "Mölndal" },
      { id: uuidv4(), name: "Mönsterås" },
      { id: uuidv4(), name: "Mora" },
      { id: uuidv4(), name: "Mörbylånga" },
      { id: uuidv4(), name: "Motala" },
      { id: uuidv4(), name: "Mullsjö" },
      { id: uuidv4(), name: "Munkedal" },
      { id: uuidv4(), name: "Munkfors" },
      { id: uuidv4(), name: "Nacka" },
      { id: uuidv4(), name: "Nässjö" },
      { id: uuidv4(), name: "Nora" },
      { id: uuidv4(), name: "Norberg" },
      { id: uuidv4(), name: "Nordanstig" },
      { id: uuidv4(), name: "Nordmaling" },
      { id: uuidv4(), name: "Norrköping" },
      { id: uuidv4(), name: "Norrtälje" },
      { id: uuidv4(), name: "Norsjö" },
      { id: uuidv4(), name: "Nybro" },
      { id: uuidv4(), name: "Nyköping" },
      { id: uuidv4(), name: "Nykvarn" },
      { id: uuidv4(), name: "Nynäshamn" },
      { id: uuidv4(), name: "Ockelbo" },
      { id: uuidv4(), name: "Öckerö" },
      { id: uuidv4(), name: "Ödeshög" },
      { id: uuidv4(), name: "Olofström" },
      { id: uuidv4(), name: "Örebro" },
      { id: uuidv4(), name: "Örkelljunga" },
      { id: uuidv4(), name: "Örnsköldsvik" },
      { id: uuidv4(), name: "Orsa" },
      { id: uuidv4(), name: "Orust" },
      { id: uuidv4(), name: "Osby" },
      { id: uuidv4(), name: "Oskarshamn" },
      { id: uuidv4(), name: "Österåker" },
      { id: uuidv4(), name: "Östersund" },
      { id: uuidv4(), name: "Östhammar" },
      { id: uuidv4(), name: "Östra Göinge" },
      { id: uuidv4(), name: "Ovanåker" },
      { id: uuidv4(), name: "Överkalix" },
      { id: uuidv4(), name: "Övertorneå" },
      { id: uuidv4(), name: "Oxelösund" },
      { id: uuidv4(), name: "Pajala" },
      { id: uuidv4(), name: "Partille" },
      { id: uuidv4(), name: "Perstorp" },
      { id: uuidv4(), name: "Piteå" },
      { id: uuidv4(), name: "Ragunda" },
      { id: uuidv4(), name: "Rättvik" },
      { id: uuidv4(), name: "Robertsfors" },
      { id: uuidv4(), name: "Ronneby" },
      { id: uuidv4(), name: "Säffle" },
      { id: uuidv4(), name: "Sala" },
      { id: uuidv4(), name: "Salem" },
      { id: uuidv4(), name: "Sandviken" },
      { id: uuidv4(), name: "Säter" },
      { id: uuidv4(), name: "Sävsjö" },
      { id: uuidv4(), name: "Sigtuna" },
      { id: uuidv4(), name: "Simrishamn" },
      { id: uuidv4(), name: "Sjöbo" },
      { id: uuidv4(), name: "Skara" },
      { id: uuidv4(), name: "Skellefteå" },
      { id: uuidv4(), name: "Skinnskatteberg" },
      { id: uuidv4(), name: "Skövde" },
      { id: uuidv4(), name: "Skurup" },
      { id: uuidv4(), name: "Smedjebacken" },
      { id: uuidv4(), name: "Söderhamn" },
      { id: uuidv4(), name: "Söderköping" },
      { id: uuidv4(), name: "Södertälje" },
      { id: uuidv4(), name: "Sollefteå" },
      { id: uuidv4(), name: "Sollentuna" },
      { id: uuidv4(), name: "Solna" },
      { id: uuidv4(), name: "Sölvesborg" },
      { id: uuidv4(), name: "Sorsele" },
      { id: uuidv4(), name: "Sotenäs" },
      { id: uuidv4(), name: "Staffanstorp" },
      { id: uuidv4(), name: "Stenungsund" },
      { id: uuidv4(), name: "Stockholm" },
      { id: uuidv4(), name: "Storfors" },
      { id: uuidv4(), name: "Storuman" },
      { id: uuidv4(), name: "Strängnäs" },
      { id: uuidv4(), name: "Strömstad" },
      { id: uuidv4(), name: "Strömsund" },
      { id: uuidv4(), name: "Sundbyberg" },
      { id: uuidv4(), name: "Sundsvall" },
      { id: uuidv4(), name: "Sunne" },
      { id: uuidv4(), name: "Surahammar" },
      { id: uuidv4(), name: "Svalöv" },
      { id: uuidv4(), name: "Svedala" },
      { id: uuidv4(), name: "Svenljunga" },
      { id: uuidv4(), name: "Täby" },
      { id: uuidv4(), name: "Tanum" },
      { id: uuidv4(), name: "Tibro" },
      { id: uuidv4(), name: "Tidaholm" },
      { id: uuidv4(), name: "Tierp" },
      { id: uuidv4(), name: "Timrå" },
      { id: uuidv4(), name: "Tingsryd" },
      { id: uuidv4(), name: "Tjörn" },
      { id: uuidv4(), name: "Tomelilla" },
      { id: uuidv4(), name: "Töreboda" },
      { id: uuidv4(), name: "Torsås" },
      { id: uuidv4(), name: "Torsby" },
      { id: uuidv4(), name: "Tranås" },
      { id: uuidv4(), name: "Tranemo" },
      { id: uuidv4(), name: "Trelleborg" },
      { id: uuidv4(), name: "Trollhättan" },
      { id: uuidv4(), name: "Trosa" },
      { id: uuidv4(), name: "Tyresö" },
      { id: uuidv4(), name: "Uddevalla" },
      { id: uuidv4(), name: "Ulricehamn" },
      { id: uuidv4(), name: "Umeå" },
      { id: uuidv4(), name: "Upplands Väsby" },
      { id: uuidv4(), name: "Upplands-Bro" },
      { id: uuidv4(), name: "Uppsala" },
      { id: uuidv4(), name: "Uppvidinge" },
      { id: uuidv4(), name: "Vadstena" },
      { id: uuidv4(), name: "Vaggeryd" },
      { id: uuidv4(), name: "Valdemarsvik" },
      { id: uuidv4(), name: "Vallentuna" },
      { id: uuidv4(), name: "Vänersborg" },
      { id: uuidv4(), name: "Vännäs" },
      { id: uuidv4(), name: "Vansbro" },
      { id: uuidv4(), name: "Vara" },
      { id: uuidv4(), name: "Varberg" },
      { id: uuidv4(), name: "Vårgårda" },
      { id: uuidv4(), name: "Värmdö" },
      { id: uuidv4(), name: "Värnamo" },
      { id: uuidv4(), name: "Västerås" },
      { id: uuidv4(), name: "Västervik" },
      { id: uuidv4(), name: "Vaxholm" },
      { id: uuidv4(), name: "Växjö" },
      { id: uuidv4(), name: "Vellinge" },
      { id: uuidv4(), name: "Vetlanda" },
      { id: uuidv4(), name: "Vilhelmina" },
      { id: uuidv4(), name: "Vimmerby" },
      { id: uuidv4(), name: "Vindeln" },
      { id: uuidv4(), name: "Vingåker" },
      { id: uuidv4(), name: "Ydre" },
      { id: uuidv4(), name: "Ystad" },
    ],
  },
  {
    id: 1,
    name: "ألمانيا",
    Countryiso: "DE",
    cities: [
      { id: uuidv4(), name: "Berlin" },
      { id: uuidv4(), name: "Stuttgart" },
      { id: uuidv4(), name: "Munich" },
      { id: uuidv4(), name: "Hamburg" },
      { id: uuidv4(), name: "Cologne" },
      { id: uuidv4(), name: "Frankfurt" },
      { id: uuidv4(), name: "Düsseldorf" },
      { id: uuidv4(), name: "Leipzig" },
      { id: uuidv4(), name: "Dortmund" },
      { id: uuidv4(), name: "Essen" },
      { id: uuidv4(), name: "Bremen" },
      { id: uuidv4(), name: "Dresden" },
      { id: uuidv4(), name: "Hannover" },
      { id: uuidv4(), name: "Duisburg" },
      { id: uuidv4(), name: "Bochum" },
      { id: uuidv4(), name: "Wuppertal" },
      { id: uuidv4(), name: "Bielefeld" },
      { id: uuidv4(), name: "Bonn" },
      { id: uuidv4(), name: "Münster" },
      { id: uuidv4(), name: "Mannheim" },
      { id: uuidv4(), name: "Karlsruhe" },
      { id: uuidv4(), name: "Nuremberg" },
      { id: uuidv4(), name: "Augsburg" },
      { id: uuidv4(), name: "Wiesbaden" },
      { id: uuidv4(), name: "Mönchengladbach" },
      { id: uuidv4(), name: "Gelsenkirchen" },
      { id: uuidv4(), name: "Aachen" },
      { id: uuidv4(), name: "Braunschweig" },
      { id: uuidv4(), name: "Chemnitz" },
      { id: uuidv4(), name: "Kiel" },
      { id: uuidv4(), name: "Halle" },
      { id: uuidv4(), name: "Magdeburg" },
      { id: uuidv4(), name: "Freiburg im Breisgau" },
      { id: uuidv4(), name: "Krefeld" },
      { id: uuidv4(), name: "Mainz" },
      { id: uuidv4(), name: "Lübeck" },
      { id: uuidv4(), name: "Erfurt" },
      { id: uuidv4(), name: "Oberhausen" },
      { id: uuidv4(), name: "Rostock" },
      { id: uuidv4(), name: "Kassel" },
      { id: uuidv4(), name: "Hagen" },
      { id: uuidv4(), name: "Potsdam" },
      { id: uuidv4(), name: "Saarbrücken" },
      { id: uuidv4(), name: "Hamm" },
      { id: uuidv4(), name: "Ludwigshafen" },
      { id: uuidv4(), name: "Mülheim" },
      { id: uuidv4(), name: "Oldenburg" },
      { id: uuidv4(), name: "Osnabrück" },
      { id: uuidv4(), name: "Leverkusen" },
      { id: uuidv4(), name: "Darmstadt" },
      { id: uuidv4(), name: "Solingen" },
      { id: uuidv4(), name: "Heidelberg" },
      { id: uuidv4(), name: "Herne" },
      { id: uuidv4(), name: "Neuss" },
      { id: uuidv4(), name: "Regensburg" },
      { id: uuidv4(), name: "Paderborn" },
      { id: uuidv4(), name: "Ingolstadt" },
      { id: uuidv4(), name: "Fürth" },
      { id: uuidv4(), name: "Würzburg" },
      { id: uuidv4(), name: "Ulm" },
      { id: uuidv4(), name: "Heilbronn" },
      { id: uuidv4(), name: "Pforzheim" },
      { id: uuidv4(), name: "Wolfsburg" },
      { id: uuidv4(), name: "Göttingen" },
      { id: uuidv4(), name: "Bottrop" },
      { id: uuidv4(), name: "Reutlingen" },
      { id: uuidv4(), name: "Koblenz" },
      { id: uuidv4(), name: "Bremerhaven" },
      { id: uuidv4(), name: "Erlangen" },
      { id: uuidv4(), name: "Recklinghausen" },
      { id: uuidv4(), name: "Bergisch Gladbach" },
      { id: uuidv4(), name: "Remscheid" },
      { id: uuidv4(), name: "Jena" },
      { id: uuidv4(), name: "Trier" },
      { id: uuidv4(), name: "Salzgitter" },
      { id: uuidv4(), name: "Moers" },
      { id: uuidv4(), name: "Siegen" },
      { id: uuidv4(), name: "Hildesheim" },
      { id: uuidv4(), name: "Gütersloh" },
      { id: uuidv4(), name: "Kaiserslautern" },
      { id: uuidv4(), name: "Schwerin" },
      { id: uuidv4(), name: "Esslingen" },
      { id: uuidv4(), name: "Ludwigsburg" },
      { id: uuidv4(), name: "Gladbeck" },
      { id: uuidv4(), name: "Rosenheim" },
      { id: uuidv4(), name: "Herten" },
      { id: uuidv4(), name: "Hilden" },
      { id: uuidv4(), name: "Elmshorn" },
      { id: uuidv4(), name: "Halle-Neustadt" },
      { id: uuidv4(), name: "Pinneberg" },
      { id: uuidv4(), name: "Siegburg" },
      { id: uuidv4(), name: "Germering" },
      { id: uuidv4(), name: "Ostfildern" },
      { id: uuidv4(), name: "Kornwestheim" },
      { id: uuidv4(), name: "Unterschleißheim" },
      { id: uuidv4(), name: "Hattersheim" },
      { id: uuidv4(), name: "Unterhaching" },
      { id: uuidv4(), name: "Weingarten" },
      { id: uuidv4(), name: "Obertshausen" },
      { id: uuidv4(), name: "Bad Soden am Taunus" },
      { id: uuidv4(), name: "Haar" },
      { id: uuidv4(), name: "Eschborn" },
      { id: uuidv4(), name: "Ottobrunn" },
      { id: uuidv4(), name: "Puchheim" },
      { id: uuidv4(), name: "Gröbenzell" },
      { id: uuidv4(), name: "Schenefeld" },
      { id: uuidv4(), name: "Wolfratshausen" },
      { id: uuidv4(), name: "Glinde" },
      { id: uuidv4(), name: "Eilendorf" },
      { id: uuidv4(), name: "Eppelheim" },
      { id: uuidv4(), name: "Neubiberg" },
      { id: uuidv4(), name: "Asperg" },
      { id: uuidv4(), name: "Wentorf bei Hamburg" },
      { id: uuidv4(), name: "Kronshagen" },
      { id: uuidv4(), name: "Eichenau" },
      { id: uuidv4(), name: "Steinbach am Taunus" },
      { id: uuidv4(), name: "Weißenthurm" },
      { id: uuidv4(), name: "Neulußheim" },
      { id: uuidv4(), name: "Eichwalde" },
      { id: uuidv4(), name: "Altbach" },
      { id: uuidv4(), name: "Merzhausen" },
      { id: uuidv4(), name: "Buckenhof" },
      { id: uuidv4(), name: "Offenbach" },
    ],
  },
  {
    id: 2,
    name: "السعودية",
    Countryiso: "SA",
    cities: [
      { id: uuidv4(), name: " الباحة ", cityiso: "11" },
      { id: uuidv4(), name: " الحدود الشمالية ", cityiso: "08" },
      { id: uuidv4(), name: " الجوف ", cityiso: "12" },
      { id: uuidv4(), name: " المدينة المنورة ", cityiso: "03" },
      { id: uuidv4(), name: " القصيم ", cityiso: "05" },
      { id: uuidv4(), name: " الرياض ", cityiso: "01" },
      { id: uuidv4(), name: " الشرقية ", cityiso: "04" },
      { id: uuidv4(), name: " عسير ", cityiso: "14" },
      { id: uuidv4(), name: " حائل ", cityiso: "06" },
      { id: uuidv4(), name: " جازان ", cityiso: "09" },
      { id: uuidv4(), name: " مكة المكرمة ", cityiso: "02" },
      { id: uuidv4(), name: " نجران ", cityiso: "10" },
      { id: uuidv4(), name: " تبوك ", cityiso: "07" },
    ],
  },
  {
    id: 3,
    name: "سوريا",
    Countryiso: "SY",
    cities: [
      { id: uuidv4(), name: "الحسكة ", cityiso: "HA" },
      { id: uuidv4(), name: "اللاذقية ", cityiso: "LA" },
      { id: uuidv4(), name: "القنيطرة ", cityiso: "QU" },
      { id: uuidv4(), name: "الرقة ", cityiso: "RA" },
      { id: uuidv4(), name: "السويداء ", cityiso: "SU" },
      { id: uuidv4(), name: "درعا ", cityiso: "DR" },
      { id: uuidv4(), name: "دير الزور ", cityiso: "DY" },
      { id: uuidv4(), name: "دمشق ", cityiso: "DI" },
      { id: uuidv4(), name: "حلب ", cityiso: "HL" },
      { id: uuidv4(), name: "حماة ", cityiso: "HM" },
      { id: uuidv4(), name: "حمص ", cityiso: "HI" },
      { id: uuidv4(), name: "ادلب ", cityiso: "ID" },
      { id: uuidv4(), name: "ريف دمشق ", cityiso: "RD" },
      { id: uuidv4(), name: "طرطوس ", cityiso: "TA" },
    ],
  },
];
