import { v4 as uuidv4 } from "uuid";

export const Qurra = [
  {
    id: uuidv4(),
    name: "إبراهيم الأخضر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/akdr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أكرم العلاقمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/akrm/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد صالح عالم شاه",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/shah/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد جبريل",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/jbrl/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد صديق المنشاوي",
    rwaia: "المصحف المعلم - المصحف المعلم",
    server: "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mo-lim/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد صديق المنشاوي",
    rwaia: "رواية اخرى",
    server: "https://server10.mp3quran.net/minsh/Almusshaf-Al-Mojawwad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد صديق المنشاوي",
    rwaia: "رواية اخرى",
    server: "https://server10.mp3quran.net/minsh/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد عبدالكريم",
    rwaia: "ورش عن نافع من طريق أبي بكر الأصبهاني - مرتل",
    server:
      "https://server12.mp3quran.net/m_krm/Rewayat-Warsh-A-n-Nafi-Men-Tariq-Abi-Baker-Alasbahani/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد عبدالكريم",
    rwaia: "رواية اخرى",
    server: "https://server12.mp3quran.net/m_krm/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد عبدالحكيم سعيد العبدالله",
    rwaia: "الدوري عن الكسائي - مرتل",
    server:
      "https://server9.mp3quran.net/abdullah/Rewayat-AlDorai-A-n-Al-Kisa-ai/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد عبدالحكيم سعيد العبدالله",
    rwaia: "رواية اخرى",
    server: "https://server9.mp3quran.net/abdullah/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود خليل الحصري",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server13.mp3quran.net/husr/Rewayat-Qalon-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود خليل الحصري",
    rwaia: "رواية اخرى",
    server: "https://server13.mp3quran.net/husr/Rewayat-Aldori-A-n-Abi-Amr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود خليل الحصري",
    rwaia: "رواية اخرى",
    server: "https://server13.mp3quran.net/husr/Rewayat-Warsh-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود خليل الحصري",
    rwaia: "رواية اخرى",
    server: "https://server13.mp3quran.net/husr/Almusshaf-Al-Mojawwad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود خليل الحصري",
    rwaia: "رواية اخرى",
    server: "https://server13.mp3quran.net/husr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود علي البنا",
    rwaia: "المصحف المجود - المصحف المجود",
    server: "https://server8.mp3quran.net/bna/Almusshaf-Al-Mojawwad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود علي البنا",
    rwaia: "رواية اخرى",
    server: "https://server8.mp3quran.net/bna/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مشاري العفاسي",
    rwaia: "رواية اخرى",
    server: "https://server8.mp3quran.net/afs/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مصطفى إسماعيل",
    rwaia: "المصحف المجود - المصحف المجود",
    server: "https://server8.mp3quran.net/mustafa/Almusshaf-Al-Mojawwad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مصطفى إسماعيل",
    rwaia: "رواية اخرى",
    server: "https://server8.mp3quran.net/mustafa/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مصطفى اللاهوني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/lahoni/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مصطفى رعد العزاوي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/ra3ad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ماجد الزامل",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/zaml/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ماهر شخاشيرو",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/shaksh/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود الشيمي",
    rwaia: "الدوري عن الكسائي - مرتل",
    server: "https://server10.mp3quran.net/sheimy/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ياسر سلامة",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/salamah/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "خالد المهنا",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/mohna/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عادل الكلباني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/a_klb/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "موسى بلال",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/bilal/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "حاتم فريد الواعر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/hatem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "إبراهيم الجرمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/jormy/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمود الرفاعي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/mrifai/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "إبراهيم الدوسري",
    rwaia: "حفص عن عاصم - مرتل",
    server:
      "https://server10.mp3quran.net/ibrahim_dosri/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "إبراهيم الدوسري",
    rwaia: "رواية اخرى",
    server:
      "https://server10.mp3quran.net/ibrahim_dosri/Rewayat-Warsh-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "الزين محمد أحمد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/alzain/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "جمعان العصيمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/jaman/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "القارئ ياسين",
    rwaia: "ورش عن نافع - مرتل",
    server: "https://server11.mp3quran.net/qari/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "يوسف بن نوح أحمد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/noah/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "معيض الحارثي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/harthi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد رشاد الشريف",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/rashad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد الطرابلسي",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server10.mp3quran.net/trablsi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد الطرابلسي",
    rwaia: "رواية اخرى",
    server: "https://server10.mp3quran.net/trabulsi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله الكندري",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/Abdullahk/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد عامر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/Aamer/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد عثمان خان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/khan/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "الدوكالي محمد العالم",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server7.mp3quran.net/dokali/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "الفاتح محمد الزبير",
    rwaia: "الدوري عن أبي عمرو - مرتل",
    server: "https://server6.mp3quran.net/fateh/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "طارق عبدالغني دعوب",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server10.mp3quran.net/tareq/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "بندر بليله",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/balilah/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "وديع اليمني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/wdee3/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "العيون الكوشي",
    rwaia: "ورش عن نافع - مرتل",
    server: "https://server11.mp3quran.net/koshi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرحمن العوسي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/aloosi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "رامي الدعيس",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/rami/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرحمن الماجد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/a_majed/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "توفيق الصايغ",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/twfeeq/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله الخلف",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server14.mp3quran.net/khalf/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "منصور السالمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server14.mp3quran.net/mansor/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "جمال شاكر عبدالله",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/jamal/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد السويلم",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server14.mp3quran.net/swlim/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "بدر التركي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/bader/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ناصر الماجد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server14.mp3quran.net/nasser_almajed/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد خليل شاهين",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/shaheen/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سعد المقرن",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/saad/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد النفيس",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/nufais/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server:
      "https://server16.mp3quran.net/deban/Rewayat-Warsh-A-n-Nafi-Men-Tariq-Alazraq/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server: "https://server16.mp3quran.net/deban/Rewayat-Aldori-A-n-Abi-Amr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server: "https://server16.mp3quran.net/deban/Rewayat-Qalon-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server:
      "https://server16.mp3quran.net/deban/Rewayat-Albizi-A-n-Ibn-Katheer/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server:
      "https://server16.mp3quran.net/deban/Rewayat-Qunbol-A-n-Ibn-Katheer/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server: "https://server16.mp3quran.net/deban/Rewayat-Sho-bah-A-n-Asim/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد ديبان",
    rwaia: "رواية اخرى",
    server: "https://server16.mp3quran.net/deban/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "خالد الجليل",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/jleel/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله كامل",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/kamel/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "بيشه وا قادر الكردي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/peshawa/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "نذير المالكي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net//nathier/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "هيثم الدخين",
    rwaia: "حفص عن عاصم - 19",
    server: "https://server16.mp3quran.net/h_dukhain/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "خالد القحطاني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/qht/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "خالد عبدالكافي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/kafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد أبو سنينة",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server16.mp3quran.net/sneineh/Rewayat-Qalon-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد الأمين قنيوة",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server16.mp3quran.net/qeniwa/Rewayat-Qalon-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد سايد",
    rwaia: "ورش عن نافع - مرتل",
    server: "https://server16.mp3quran.net/m_sayed/Rewayat-Warsh-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالإله بن عون",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/a_binaoun/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "نورين محمد صديق",
    rwaia: "الدوري عن أبي عمرو - مرتل",
    server:
      "https://server16.mp3quran.net/nourin_siddig/Rewayat-Aldori-A-n-Abi-Amr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله عبدل",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/a_abdl/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مروان العكري",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server16.mp3quran.net/m_akri/Rewayat-Qalon-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد عيسى المعصراوي",
    rwaia: "رواية اخرى",
    server:
      "https://server16.mp3quran.net/a_maasaraawi/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "إبراهيم كشيدان",
    rwaia: "قالون عن نافع - مرتل",
    server: "https://server16.mp3quran.net/i_kshidan/Rewayat-Qalon-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "هاشم أبو دلال",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/h_abudalal/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "خليفة الطنيجي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/tnjy/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "فؤاد الخامري",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/f_khamery/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سيد أحمد هاشمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/s_hashemi/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "خالد كريم محمدي",
    rwaia: "حفص عن عاصم - مرتل",
    server:
      "https://server16.mp3quran.net/kh_mohammadi/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "صالح الشمراني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/shamrani/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "مال الله عبدالرحمن الجابر",
    rwaia: "حفص عن عاصم - مرتل",
    server:
      "https://server16.mp3quran.net/mal-allah_jaber/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سلمان الصديق",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/s_sadeiq/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "حسن صالح",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/h_saleh/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرحمن الشحات",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/a_alshahhat/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "فيصل الهاجري",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/f_hajry/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أنس العمادي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/a_alemadi/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "رشيد بلعالية",
    rwaia: "رواية اخرى",
    server: "https://server6.mp3quran.net/bl3/Rewayat-Warsh-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالكريم الحازمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/a_alhazmi/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "هشام الهراز",
    rwaia: "ورش عن نافع - مرتل",
    server: "https://server16.mp3quran.net/H-Lharraz/Rewayat-Warsh-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سعد الغامدي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server7.mp3quran.net/s_gmd/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سعود الشريم",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server7.mp3quran.net/shur/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سهل ياسين",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/shl/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "زكي داغستاني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/zaki/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "سيد رمضان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/sayed/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "شيرزاد عبدالرحمن طاهر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/taher/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "صابر عبدالحكم",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/hkm/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "شيخ أبو بكر الشاطري",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/shatri/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "صالح الهبدان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/habdan/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "صلاح البدير",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/s_bud/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "صلاح الهاشم",
    rwaia: "رواية اخرى",
    server: "https://server12.mp3quran.net/salah_hashim_m/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "صلاح بو خاطر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/bu_khtr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عادل ريان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/ryan/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالبارئ الثبيتي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/thubti/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالبارئ محمد",
    rwaia: "رواية اخرى",
    server: "https://server12.mp3quran.net/bari/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالباسط عبدالصمد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server7.mp3quran.net/basit/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالباسط عبدالصمد",
    rwaia: "رواية اخرى",
    server: "https://server7.mp3quran.net/basit/Rewayat-Warsh-A-n-Nafi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالباسط عبدالصمد",
    rwaia: "رواية اخرى",
    server: "https://server7.mp3quran.net/basit/Almusshaf-Al-Mojawwad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرحمن السديس",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/sds/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد بن علي العجمي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server10.mp3quran.net/ajm/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالعزيز الأحمد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/a_ahmed/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالعزيز الزهراني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/zahrani/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله المطرود",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/mtrod/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله بصفر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/bsfr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله خياط",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/kyat/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله عواد الجهني",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server13.mp3quran.net/jhn/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالله غيلان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/gulan/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرشيد صوفي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server16.mp3quran.net/soufi/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرشيد صوفي",
    rwaia: "رواية اخرى",
    server: "https://server16.mp3quran.net/soufi/Rewayat-Assosi-A-n-Abi-Amr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالرشيد صوفي",
    rwaia: "رواية اخرى",
    server: "https://server16.mp3quran.net/soufi/Rewayat-Khalaf-A-n-Hamzah/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد الحواشي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/hawashi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالمحسن الحارثي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/mohsin_harthi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالمحسن القاسم",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/qasm/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالمحسن العبيكان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/obk/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالهادي أحمد كناكري",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/kanakeri/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عبدالودود حنيف",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/wdod/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "علي بن عبدالرحمن الحذيفي",
    rwaia: "شعبة  عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/hthfi/Rewayat-Sho-bah-A-n-Asim/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "علي بن عبدالرحمن الحذيفي",
    rwaia: "رواية اخرى",
    server: "https://server9.mp3quran.net/huthifi_qalon/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "علي بن عبدالرحمن الحذيفي",
    rwaia: "رواية اخرى",
    server: "https://server9.mp3quran.net/hthfi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "علي جابر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/a_jbr/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "علي حجاج السويسي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/hajjaj/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عماد زهير حافظ",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/hafz/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "عمر القزابري",
    rwaia: "ورش عن نافع - مرتل",
    server: "https://server9.mp3quran.net/omar_warsh/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "فارس عباد",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/frs_a/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ناصر القطامي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server6.mp3quran.net/qtm/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد صابر",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/saber/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "نبيل الرفاعي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/nabil/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "نعمة الحسان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/namh/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "هاني الرفاعي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/hani/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "وليد النائحي",
    rwaia: "قالون عن نافع من طريق أبي نشيط - مرتل",
    server: "https://server9.mp3quran.net/waleed/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ياسر الدوسري",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/yasser/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ياسر القرشي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/qurashi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ياسر المزروعي ",
    rwaia: "قراءة يعقوب الحضرمي بروايتي رويس وروح - مرتل",
    server: "https://server9.mp3quran.net/mzroyee/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "يحيى حوا",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/yahya/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "أحمد نعينع",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server11.mp3quran.net/ahmad_nu/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "يوسف الشويعي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server9.mp3quran.net/yousef/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ماهر المعيقلي",
    rwaia: "المصحف المجود - المصحف المجود",
    server: "https://server12.mp3quran.net/maher/Almusshaf-Al-Mojawwad/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "ماهر المعيقلي",
    rwaia: "رواية اخرى",
    server: "https://server12.mp3quran.net/maher/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد الطبلاوي",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server12.mp3quran.net/tblawi/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد اللحيدان",
    rwaia: "حفص عن عاصم - مرتل",
    server: "https://server8.mp3quran.net/lhdan/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد أيوب",
    rwaia: "حفص عن عاصم - 19",
    server: "https://server16.mp3quran.net/ayyoub2/Rewayat-Hafs-A-n-Assem/",
    surah_total: 114,
  },
  {
    id: uuidv4(),
    name: "محمد أيوب",
    rwaia: "رواية اخرى",
    server: "https://server8.mp3quran.net/ayyub/",
    surah_total: 114,
  },
];
