[
  "Abdulaziz Az-Zahrani",
  "AbdulBari ath-Thubaity",
  "Abdul Bari Mohammed",
  "AbdulBaset AbdulSamad [Mujawwad]",
  "AbdulBaset AbdulSamad [Murattal]",
  "Abdul-Kareem al-Hazmi",
  "Abdullah al-Matrood",
  "Abdullah Juhany",
  "Abdullah Basfar",
  "Abdullah Khayat",
  "Abdullah Khulayfee",
  "Abdulmohsen Al-Harthy",
  "AbdulMuhsin al-Qasim",
  "Abdul-Mun'im Abdul-Mubdi'",
  "AbdulWadood Haneef",
  "Abdur-Rashid Sufi [Abi al-Haarith an al-Kasaa’ee]",
  "Abdur-Rashid Sufi [ad-Doori an Abi Amr]",
  "Abdur-Rashid Sufi [Shu'bah an Asim]",
  "Abdurrashid Sufi [Soosi]",
  "Abdur Razaq Bin Abtan Al Dulaimi",
  "Abu Abdullah Munir Al Tounsi",
  "Abu Bakr al Dhabi",
  "Adel Kalbani",
  "Ahmad Al Hawashy",
  "Ahmad Alnufais",
  "Ahmad Khader Al-Tarabulsi",
  "Ahmad Suleiman",
  "Ahmed ibn Ali al-Ajamy",
  "Ahmed Al Hammad",
  "Ahmed Al Misbahi",
  "Ahmed Amir",
  "Ahmed Mohamed Salama",
  "Ahmed Saber",
  "Mishary Rashid Alafasy",
  "Al Ashry Omran",
  "Al Fateh Muhammad Zubair",
  "Al Husayni Al Azazi",
  "Al Husayni Al Azazi - Children",
  "Ali Abdur-Rahman al-Huthaify",
  "Ali al-Huthaify [Qaaloon]",
  "Ali Hajjaj Souissi",
  "Alzain Mohammad Ahmad",
  "Ayman Swed",
  "Aziz Alili",
  "Bandar Balila",
  "Bassel Abdul Rahman Raoui",
  "عبد المجيب بن كيران",
  "Darwish Faraj Darwish Al Attar",
  "Eid Hassan Abu Aachra",
  "Emad Al Mansary",
  "Ezzat Sabri",
  "Fares Abbad",
  "Fouad Al Khamiri",
  "Hamad Sinan",
  "Hamdy Al Sayed Tolba Saad",
  "Hani ar-Rifai",
  "Hasan Hashem",
  "Hasan Saleh",
  "hatemfarid",
  "Ibrahim Al Akhdar",
  "Ibrahim Al Dossari",
  "Ibrahim Aljormy",
  "Ilhan Tok",
  "Imad Zuhair Hafez",
  "Jaber Abdul Hameed",
  "Jamaan Alosaimi",
  "Jamal Shaker Abdullah",
  "Jazza Alswaileh",
  "Abdallah Kamel",
  "Karim Mansouri",
  "Khaalid Abdullaah al-Qahtaanee",
  "Khaled Barakat",
  "Khalid Abdulkhafi",
  "Khalid Al Jalil",
  "Khalid Al-Moh'n'na",
  "Khalifah At-Tonaeijy",
  "Laayoun El Kouchi",
  "Le Saint Coran Traduit En Francais",
  "Maher Shakhashero",
  "Mahmod Alrifai",
  "Mahmud Ali Al Banna",
  "Mahmoud El Sheimy",
  "Mahmoud Saad Darouich",
  "Mahmoud Sayed Eltayeb",
  "Mishary Rashid Alafasy",
  "Moeedh Al-Harthi",
  "Mohamed Abdelaziz",
  "Mohamed Abdel Hakim Saad Al Abdullah",
  "Mohamed Aljabery Al Heyani",
  "Mohamed Al Mohisni",
  "Mohamed El Kantaoui",
  "Muhammad Hassan",
  "Mohamed Maabad",
  "Mohammed Osman Khan (from India)",
  "Mohamed Shaaban Abu Qarn",
  "Mohamed Al-Tablawi",
  "Mohammad Ismaeel Al-Muqaddim",
  "Mohammad Rachad Al Shareef",
  "Mohammed Bin Saleh Abu Zaid",
  "Moftah AlSultany",
  "Muhammad AbdulKareem",
  "Muhammad Al Aalim Al Dokali",
  "Mohammad Al-Haid'an",
  "Muhammad al-Muhaisny",
  "Muhammad Subbayil",
  "Muhammad Anwar Shahat",
  "Mohammad Ayyub",
  "Mohammad Saleh Shah",
  "Muhammad Siddeeq al-Minshawi [Mujawwad]",
  "Muhammad Sulaiman Patel",
  "Musa Bilal",
  "Mustafa Al-Lahoni",
  "Mostafa Ismaeel",
  "Mustafa Ra'ad Al-Azawi",
  "Mustapha Gharbi",
  "Nabil Ar-Rifa'i",
  "Nasser Alqatami",
  "N'amah Alhassan",
  "Abdul Mohsen Al Obeikan",
  "Oimao Qataris",
  "Omar Al Kazabri",
  "Osama Bin Ali Al Ghanim",
  "Rachid Belalia",
  "Saber Abdul-hakam",
  "Sadaqat Ali",
  "Sahl Yaaseen",
  "Said Al Shaalan",
  "Salah Al-Budair",
  "Salah Alhashim",
  "Salah Baothman",
  "Samir Belaachya",
  "Sa'ud al-Shuraym",
  "Sheikh Syed Ramadan",
  "Shahriar Parhizgar",
  "Shaykh Sudais and Shaykh Shuraim with Naeem Sultan [Pickthall Translation]",
  "Tamer Islam",
  "Tareq Daawob",
  "Tawfeeq As-Sayegh",
  "Turki Ebeid Al Marri",
  "Wael Desouky",
  "Wael Radwan Qureshi",
  "Waleed Idrees Al Maneese",
  "Waleed AlNa'ehi",
  "Waleed Samir Ali Abdul Majid Sorour",
  "Walid Al Shatti",
  "Walid Fathi Bashta",
  "Yahya Hawwa",
  "Yassen Al Jazairi",
  "Yasser Al_Dosari",
  "Yasser Al-Mazroey",
  "Yasser AlKurashy",
  "Yasser Salama",
  "Yasser Sarhan Eldeeb",
  "Yousef Al-Shoowayie'e",
  "Yusuf Bin Noah Ahmed",
  "Mishaari Raashid with Ibrahim Walk [Saheeh Intl Translation]",
  "Muhammad Ayoob with Mikaal Waters [Muhsin Khan Translation]",
  "Sodais and Shuraim with Aslam Athar [Pickthall Translation]",
];
